import Head from "next/head";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import Message from "../components/Message";
import { useEffect, useState } from "react";
import { auth, db } from "./../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { useAuthState } from "react-firebase-hooks/auth";
import Link from "next/link";

export default function Home() {
  //create  a state with all post
  const [allPosts, setAllPosts] = useState([]);
  const gatPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    //if a post update we can see it without reloading the page
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(),id:doc.id })));
    });
    return unsubscribe;
  };
  useEffect(()=>{
    gatPosts()
  },[])
  return (
    <div className={styles.container } >

    <div className="bg-[#1e293b] h-screen">
       <Head>
        <title>Creative Minds </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className=" text-lg font-meduim py-4 bg-[#1e293b]">
        
        <h2 className="text-white mb-4 mx-3">Other people posts :</h2>
        <div className="flex flex-col gap-4 items-center mb-4 ">
          {allPosts.map((post) => (
        <Message {...post} key={post.id} >
          <Link href={{pathname:`/${post.id}`,query:{...post}}}>
            <button className=" text-black  rounded-md">{post.comments?.length> 0 ?post.comments?.length:"0"} Comments</button>
          </Link>
        </Message>))}
        </div>
        
      </div>
    </div>
    </div>
     
  );
}
